apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-root
spec:
  generators:
  - list:
      elements:
      - name: nginx
        stage: test
        repoUrl: https://github.com/mrjerzy/app-nginx.git
        targetRevision: HEAD
      - name: nginx
        stage: prod
        repoUrl: https://github.com/mrjerzy/app-nginx.git
        targetRevision: v0.0.1
  template:
    metadata:
      name: '{{name}}-{{stage}}'
    spec:
      project: default
      source:
        repoURL: '{{repoUrl}}'
        targetRevision: '{{targetRevision}}'
        path: deployment/{{name}}/{{stage}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{name}}-{{stage}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
